# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths C:/Users/byim/Documents/ENSC_452/Milestone2/rannum/managed_ip_project/randNum_1.0 [current_fileset]
read_vhdl {
  C:/Users/byim/Documents/ENSC_452/Milestone2/rannum/managed_ip_project/randNum_1.0/hdl/randNum_v1_0_S_AXI.vhd
  C:/Users/byim/Documents/ENSC_452/Milestone2/rannum/managed_ip_project/randNum_1.0/hdl/randNum_v1_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/byim/Documents/ENSC_452/Milestone2/rannum/managed_ip_project/edit_randNum_v1_0.data/wt [current_project]
set_property parent.project_dir C:/Users/byim/Documents/ENSC_452/Milestone2/rannum/managed_ip_project [current_project]
synth_design -top randNum_v1_0 -part xc7z020clg484-1
write_checkpoint randNum_v1_0.dcp
report_utilization -file randNum_v1_0_utilization_synth.rpt -pb randNum_v1_0_utilization_synth.pb
