# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  c:/Users/byim/Documents/ENSC_452/MILESTONE_6/zed_audio_ctrl
  c:/Users/byim/Documents/ENSC_452/MILESTONE_6/joystk2
  c:/Users/byim/Documents/ENSC_452/MILESTONE_6/vga250
  C:/Users/byim/Documents/ENSC_452/MILESTONE_6/rannum
  c:/Users/byim/Documents/ENSC_452/MILESTONE_6/led_ip
} [current_fileset]

add_files C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_1_2/system_axi_gpio_1_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_1_2/system_axi_gpio_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_axi_gpio_1_2/system_axi_gpio_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_auto_pc_62/system_auto_pc_62_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/ip/system_auto_pc_63/system_auto_pc_63_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/system.bd]

read_verilog C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/imports/lab4/zed_audio_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/imports/lab4/zed_audio_constraints.xdc]

read_xdc C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/new/led_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/new/led_constraints.xdc]

read_xdc C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/new/zed_vga_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/new/zed_vga_constraints.xdc]

read_xdc C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/new/joystick_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.srcs/constrs_1/new/joystick_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame/mainGame.data/wt [current_project]
set_property parent.project_dir C:/Users/byim/Documents/ENSC_452/MILESTONE_6/mainGame [current_project]
synth_design -top system_wrapper -part xc7z020clg484-1
write_checkpoint system_wrapper.dcp
report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb
