
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.3 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_GPIO_0_DEVICE_ID,
		XPAR_AXI_GPIO_0_BASEADDR,
		XPAR_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_BTNS_5BIT_DEVICE_ID,
		XPAR_BTNS_5BIT_BASEADDR,
		XPAR_BTNS_5BIT_INTERRUPT_PRESENT,
		XPAR_BTNS_5BIT_IS_DUAL
	},
	{
		XPAR_SW_8BITS_DEVICE_ID,
		XPAR_SW_8BITS_BASEADDR,
		XPAR_SW_8BITS_INTERRUPT_PRESENT,
		XPAR_SW_8BITS_IS_DUAL
	}
};


