############################
# On-board LED             #
############################
set_property PACKAGE_PIN T22 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN T21 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U22 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN U21 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN V22 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN W22 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U19 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN U14 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bit_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bit_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bit_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bit_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bit_tri_io[0]}]
set_property PACKAGE_PIN T18 [get_ports {btns_5bit_tri_io[4]}]
set_property PACKAGE_PIN R18 [get_ports {btns_5bit_tri_io[3]}]
set_property PACKAGE_PIN N15 [get_ports {btns_5bit_tri_io[2]}]
set_property PACKAGE_PIN R16 [get_ports {btns_5bit_tri_io[1]}]
set_property PACKAGE_PIN P16 [get_ports {btns_5bit_tri_io[0]}]
set_property PACKAGE_PIN M15 [get_ports {sw_8bits_tri_io[7]}]
set_property PACKAGE_PIN H17 [get_ports {sw_8bits_tri_io[6]}]
set_property PACKAGE_PIN H18 [get_ports {sw_8bits_tri_io[5]}]
set_property PACKAGE_PIN H19 [get_ports {sw_8bits_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[4]}]
set_property PACKAGE_PIN F21 [get_ports {sw_8bits_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[3]}]
set_property PACKAGE_PIN H22 [get_ports {sw_8bits_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[2]}]
set_property PACKAGE_PIN G22 [get_ports {sw_8bits_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[1]}]
set_property PACKAGE_PIN F22 [get_ports {sw_8bits_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_8bits_tri_io[7]}]
