# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths c:/Users/jcleong/Documents/EmbeddedSysDes/labsource/labs/led_ip/led_ip_1.0 [current_fileset]
read_verilog {
  C:/Users/jcleong/Documents/EmbeddedSysDes/labsource/labs/led_ip/managed_ip_project/edit_led_ip_v1_0.srcs/sources_1/imports/lab3/lab3_user_logic.v
  c:/Users/jcleong/Documents/EmbeddedSysDes/labsource/labs/led_ip/led_ip_1.0/hdl/led_ip_v1_0_S_AXI.v
  c:/Users/jcleong/Documents/EmbeddedSysDes/labsource/labs/led_ip/led_ip_1.0/hdl/led_ip_v1_0.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jcleong/Documents/EmbeddedSysDes/labsource/labs/led_ip/managed_ip_project/edit_led_ip_v1_0.data/wt [current_project]
set_property parent.project_dir C:/Users/jcleong/Documents/EmbeddedSysDes/labsource/labs/led_ip/managed_ip_project [current_project]
synth_design -top led_ip_v1_0 -part xc7vx485tffg1157-1
write_checkpoint led_ip_v1_0.dcp
report_utilization -file led_ip_v1_0_utilization_synth.rpt -pb led_ip_v1_0_utilization_synth.pb
